#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libconfig
Version  : 1.5
Release  : 10
URL      : http://www.hyperrealm.com/libconfig/libconfig-1.5.tar.gz
Source0  : http://www.hyperrealm.com/libconfig/libconfig-1.5.tar.gz
Summary  : C++ Configuration File Library
Group    : Development/Tools
License  : LGPL-2.1
Requires: libconfig-lib
Requires: libconfig-doc
BuildRequires : bison
BuildRequires : cmake
BuildRequires : flex

%description


%package dev
Summary: dev components for the libconfig package.
Group: Development
Requires: libconfig-lib

%description dev
dev components for the libconfig package.


%package doc
Summary: doc components for the libconfig package.
Group: Documentation

%description doc
doc components for the libconfig package.


%package lib
Summary: lib components for the libconfig package.
Group: Libraries

%description lib
lib components for the libconfig package.


%prep
%setup -q -n libconfig-1.5

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
./tests/libconfig_tests

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/*.h\+\+
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/info/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
